seetings_default_param = {
    "consumer_based_on_tariff": False,
    "consumer_connection_limit": False,
    "solver_name": "gurobi",
    "flex_dem_active_for_consumer": True,
    "share_of_flexibly_charging_EV": 0.5,  # Share of total EV consumption that is flexible (0-1). The remaining (1-share) is inflexible.
    "V2G_share_of_flexibly_charging_EV": 0.5,
    "reduce_DH_demand_by_[MWh]": 0,
    "CH_only": False,
    "neighbor_countries_for_CH_only_mode": ["DE00", "AT00", "FR00", "IT00"],
    "neighbor_price_scenario_for_CH_only_mode": "default",
    "t_start": 6553,
    "t_end": 6552,
    "consumer_start": 1,
    "consumer_end": 300,
    "opt_mode": "core",
    "consumers_representing": 8230,
    "reduce_DH_demand_by_[MWh]": 0.0,
    "slack_soc": False,
    "single_large_battery": True,
    "winter_limit": {"mode": False, "window": [6553, 2184], "energy_MWh": 5 * 1000000},
    "rep_hydro_plants": True,
    "allow_investment": True,
    "merge_some_countries": True,
    "target_merge_countries": ["IT", "LU"],
    "minimum_RES_target_CH": False,
    "cost_op_match_nexuse": False,
    "RES_CH_coefficient": 1,
    "PVRF_CH_coefficient": 1,
    "Windon_CH_coefficient": 1,
    "limit_fuel_import_CH": False,
    "limited_fuels_import_CH_list": ["resmethane", "fossilmethane", ],
    "ror_annual_TWh" : False,
    "hydro_inflow_TWh" : False,
    "pump_capacity_GW" : False,
    "adding_hydro_storage_cap_TWh" : False,
    "reduce_inflex_demand_by_[MWh]" : 0,
    "lost_load_cost_mode": "single_step",  # 'single_step' (default) or 'multi_step_v1' for stepwise lost load cost
    "flexible_household_heatpump_share" : 0.5,
    "heat_flexibility_Kelvin": 0.5,  # Degree of flexibility for heat pumps (in Kelvin)
    "share_of_available_charging_capacity_for_V2G": 0.7,
    "NodeDH_list": ['DH_medium', 'DH_Mittelland', 'DH_Alpen', 'DH_Jura', 'DH_Voralpen', 'ILLT_Mittelland', 'ILLT_Alpen', 'ILLT_Jura', 'ILLT_Voralpen', 'ILLT_Alpensuedseite', 'ILHT_Mittelland', 'ILHT_Alpen', 'ILHT_Jura', 'ILHT_Voralpen', 'ILHT_Alpensuedseite',],
    "storage_to_charge_ratio_days": 7,
    "battery_cost_factor": 1,
    "battery_investment_nodes_in_addition_to_CH": "",
    "reduce_BE_FR_day_nine_and_ten_demand_to_percent": 1.0,
    "resistive_heater_investment_cap_MW_total": False,  # MW limit for total resistive heater investment across all nodes
    "electrolyzer_demand_reduction_coefficient": 1,
    "NTC_CH_ratio": 1,
    "RES_EU_coefficient": 1.1,
    "weather_year": 1995,
    "run_year": 2050,
    "eu_policy": "GA",
    "ch_policy": "ZBA",
    "Node_list_setting": [
        "CH00",
        "IT00",
        "DE00",
        # "DEKF",  # ?
        "FR00",
        "AT00",
        "DKE1",  # ?
        "DKW1",  # ?
        # "DKKF", # ?
        "BE00",
        "CZ00",
        "ES00",
        "UK00",
        "HU00",
        "LU00",
        "NL00",
        "PL00",
        "PT00",
        "SI00",
        "SK00",
        "HR00",
        "SE01",
        "SE02",
        "SE03",
        "SE04",
        "NON1",
        "NOM1",
        "NOS0",
    ],
}
